### ISSUE TITLE
Error creating GedcomX graph.

### ISSUE THREAD

**Issue by crapo** [youngtai/gedcomx-differ-react#3]
I now get an error from the Differ (https://youngtai.github.io/gedcomx-differ-react/) on any two files created with GEDCOMX Viewer. The two attached are a simple example. The message in the console is
2GraphView.js:22 Error creating GedcomX graph: TypeError: Cannot read properties of undefined (reading 'person')
    at addOtherRelationshipsToPersonNodes (RelationshipGraph.js:316:35)
    at addFamilyNodes (RelationshipGraph.js:468:3)
    at new RelationshipGraph (RelationshipGraph.js:502:3)
    at GraphView.js:12:23
    at rs (react-dom.production.min.js:244:332)
    at Sc (react-dom.production.min.js:286:111)
    at sc (react-dom.production.min.js:273:185)
    at Go (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:283:470
    at wc (react-dom.production.min.js:281:398)
[GVEntered1.json](https://github.com/youngtai/gedcomx-differ-react/files/15485260/GVEntered1.json)
[GVEntered2.json](https://github.com/youngtai/gedcomx-differ-react/files/15485261/GVEntered2.json)

The graph seems to be rendered appropriately, but then a call is made where gx has no persons and no relationships.

**Comment by youngtai** [comment]
I don't think this is an issue any more. At least these examples didn't have problems. Also it looks like the error lies in the GedcomX graph code rather than the differ code itself.
