### ISSUE TITLE
Fails to load these files saved by GEDCOM-X Viewer

### ISSUE THREAD

**Issue by crapo** [youngtai/gedcomx-differ-react#8]
These two files load just find in the Viewer. I saved them each from the Viewer after I had trouble loading them into the Differ. 
[009021414_01059-2-B.json](https://github.com/user-attachments/files/15930541/009021414_01059-2-B.json)
[009021414_01059-2-A.json](https://github.com/user-attachments/files/15930542/009021414_01059-2-A.json)

They loaded fine in the GEDCOM-X Viewer with out any Persons in either. Without Persons there was an error in PersonsDiff.js line 203, leftPersons was undefined. So I added Persons to each in the Viewer and saved them. After that they still didn't load but the error was different:

console.js:273 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Boriginal%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at $i (react-dom.production.min.js:152:60)
    at e (react-dom.production.min.js:162:372)
    at wl (react-dom.production.min.js:192:308)
    at ks (react-dom.production.min.js:294:9)
    at bc (react-dom.production.min.js:280:389)
    at gc (react-dom.production.min.js:280:320)
    at hc (react-dom.production.min.js:280:180)
    at ic (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)

**Comment by youngtai** [comment]
@crapo I just made a fix for this here: https://github.com/youngtai/gedcomx-differ-react/commit/ca5bcce9ba24dbdb3d1bcecf1701891e91817c5a
